initial version
hankaEsha/fizzbuzz pull request #1
Opened 2022-04-08 17:18 UTC by hankaEsha

2022-04-11 12:03 UTC, katemihalikova requested changes
PR se mi líbí, dobrá práce :+1: Napadlo mě jen pár detailů, jde spíš o nápady než vyloženě chyby.

2022-04-11 12:03 UTC, katemihalikova commented on fizzbuzz.js
> +            // pokud neni delitelne 3 - NE
Mate mě dvojitý zápor - je tedy dělitelné 3 nebo není? :)

2022-04-11 12:03 UTC, katemihalikova commented on fizzbuzz.js
> +    console.log(checkedValue);
Zapomenutý `console.log`

2022-04-11 12:03 UTC, katemihalikova commented on fizzbuzz.js
> +function areArraysIdentical(array1, array2) {
Tahle funkce je použitá jen níže v zakomentovaném kódu, jestli je to jen debugovací kód, tak nejlépe smazat.

2022-04-11 12:03 UTC, katemihalikova commented on fizzbuzz.js
> +            numberListItem.innerHTML = item;
Když se do elementu přidává nějaký čistý text, `textContent` je lepší než `innerHTML` (to si nechej jen pro "smazání všeho obsahu z elementu").

2022-04-11 12:03 UTC, katemihalikova commented on fizzbuzz.js
> +        renderArray(fizzbuzzByOptionalFigure(listLength));
`fizzbuzzByOptionalFigure` obsahuje nějaké základní ověření vstupu (`listLength`) - když nevyhovuje, vrátí nějakou chybu. Tady je pak nadbytečné řešit zpracování vstupu ještě znovu (pomocí `Number.parseInt`). Nebála bych se tady vůbec neřešit konkrétní obsah inputu a jen hodnotu z něj poslat dál. Je to input typu `number`, tak by tě mohla zajímat [vlastnost `valueAsNumber`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#valueasnumber) (automaticky to převede hodnotu z inputu na číslo), takže by pak tahle část kódu vypadala takto:

```javascript
const listLength = document.getElementById("input").valueAsNumber;
renderArray(fizzbuzzByOptionalFigure(listLength));
```

2022-04-11 12:03 UTC, katemihalikova commented on index.html
> +                    >
Elementy jsou tu velmi zajímavě naformátované 🤔 To ti dělá nějaký automatický formátovač?

2022-04-11 12:03 UTC, katemihalikova commented on style.css
> +.fizzbuzz {
Líbilo by se mi víc `.fizz.buzz`, ale to už je jen můj pocit, nemusíš to měnit. Kdyby ses rozhodla to změnit, může se hodit metoda řetězce [`includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes).

2022-04-12 04:55 UTC, benabraham commented on fizzbuzz.js
> +            // pokud neni delitelne 3 - NE
doplním, že se to týká toho komentáře

2022-04-12 04:59 UTC, benabraham commented on index.html
> +                    >
Prettier… chtělo by mu pomoct ručním zalomením.
Nechce dát whitespace, když nemá jak vědět, jestli může.

2022-04-12 20:20 UTC, benabraham requested changes
I'd change a thing or two.

2022-04-12 20:20 UTC, benabraham commented on fizzbuzz.js
>  const fizzbuzzAlgoritmus1 = () => {
Shouldn't this be in English too? i.e. `fizzbuzzAlgorithm1` etc.?

2022-04-12 20:20 UTC, benabraham commented on fizzbuzz.js
> +        } // did not followed any of the previous conditions
better english
```suggestion
        } // did not follow any of the previous conditions
```
or even clearer
```suggestion
        } // NOT a multiply of 3 nor 5
```

2022-04-12 20:20 UTC, benabraham commented on fizzbuzz.js
> +Slyle Fizz, Buzz and FizzBuzz at the list
fix errors
```suggestion
Style Fizz, Buzz and FizzBuzz in the list
```
or even better
```suggestion
Make Fizz, Buzz and FizzBuzz look differently in the list.
```

2022-04-12 20:20 UTC, benabraham commented on fizzbuzz.js
> +Add an option to set the number of listings
```suggestion
Add an option to set the number of generated items.
```

2022-04-12 20:20 UTC, benabraham commented on fizzbuzz.js
> +    // check of input
```suggestion
    // check the input for …
```
for what?

2022-04-12 20:20 UTC, benabraham commented on fizzbuzz.js
> +);
Cool! 

What about adding a generated array and compare all the variants to it?

2022-04-12 20:20 UTC, benabraham commented on fizzbuzz.js
>      for (let i = 1; i <= 50; i++) {
Still not happy with the lower number. It could be just 100 again and it would be easier to compare and easier to show. Yes it would visually look the same as other options but why not?

2022-04-14 09:18 UTC, merged